version: '3.7'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Tech'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'newuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'Toor@123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  web:
    image: tech:latest
    restart: always
    ports:
      - "10001:10001"
    expose:
      # Opens port 3306 on the container
      - '10001'
      # Where our data will be persisted
    depends_on:
       - db
# Names our volume
volumes:
    my-db: {}
